### PR TITLE
tag UDP ports in use properly so they get closed correctly

### LINKED ISSUE #1470: UDP:out error requires node-red restart after deployment
With a UDP sender node, I have to restart node-red after each redeployment, because of the error thrown when I hit Deploy button (after that UDP sender does not work). I am using it with a preceding OSC node (node-red-contrib-osc), but the error is thrown regardless of OSC. I have confirmed it both on ubuntu and OSX. The flow is attached.

The error:

```
30 Oct 10:54:49 - [info] Node-RED version: v0.17.5
30 Oct 10:54:49 - [info] Node.js  version: v7.10.1
30 Oct 10:54:49 - [info] Linux 4.4.0-72-generic x64 LE
30 Oct 10:54:50 - [info] Loading palette nodes
30 Oct 10:54:50 - [warn] ------------------------------------------------------
30 Oct 10:54:50 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
30 Oct 10:54:50 - [warn] ------------------------------------------------------
30 Oct 10:54:50 - [info] Settings file  : /home/vgusev/.node-red/settings.js
30 Oct 10:54:50 - [info] User directory : /home/vgusev/.node-red
30 Oct 10:54:50 - [info] Flows file     : /home/vgusev/.node-red/flows_dellgv.json
30 Oct 10:54:50 - [info] Server now running at http://127.0.0.1:1880/
30 Oct 10:54:50 - [info] Starting flows
30 Oct 10:54:50 - [info] Started flows
30 Oct 10:54:50 - [info] [udp out:65bd6199.7fee1] udp broadcast ready: 3000 -> 255.255.255.255:3000
30 Oct 10:54:50 - [info] [udp in:e00d1277.83cb9] udp listener at 0.0.0.0:3001
30 Oct 10:55:29 - [info] Stopping flows
30 Oct 10:55:29 - [info] [udp out:65bd6199.7fee1] udp output stopped
30 Oct 10:55:29 - [info] [udp in:e00d1277.83cb9] udp listener stopped
30 Oct 10:55:29 - [info] Stopped flows
30 Oct 10:55:29 - [info] Starting flows
**30 Oct 10:55:29 - [error] [udp out:65bd6199.7fee1] Error: Not running**
30 Oct 10:55:29 - [info] Started flows
30 Oct 10:55:29 - [info] [udp in:e00d1277.83cb9] udp listener at 0.0.0.0:3001
```
[flows_dellgv.json.zip](https://github.com/node-red/node-red/files/1426385/flows_dellgv.json.zip)

### PR DESCRIPTION
**Pull request by dceejay**
PR to close #1470

### CODE REVIEW

File: nodes/core/io/32-udp.js [hunk 1]
```diff
@@ -126,7 +126,7 @@ module.exports = function(RED) {
 
         var sock;
         if (udpInputPortsInUse[this.outport]) {
-            sock = udpInputPortsInUse[this.outport];
+            sock = udpInputPortsInUse[this.outport || this.port];
```
Comment (knolleary) [inline nodes/core/io/32-udp.js]: If `this.outport` isn't defined then we won't be in this `if` block for this change to have any affect. The `if` statement on line 128 need to change to match.

Comment (dceejay) [reply nodes/core/io/32-udp.js]: good catch - thanks

File: nodes/core/io/32-udp.js [hunk 2]
```diff
@@ -199,7 +199,7 @@ module.exports = function(RED) {
 
         node.on("close", function() {
             if (udpInputPortsInUse.hasOwnProperty(node.outport)) {
-                delete udpInputPortsInUse[node.outport];
+                delete udpInputPortsInUse[node.outport || node.port];
```
Comment (knolleary) [inline nodes/core/io/32-udp.js]: This is another `if` statement that needs to include the `|| node.port` check
