### PR TITLE
Ensure storage/util.writeFile handles concurrent write attempts

### LINKED ISSUE #4221: Uncaught exception when writing .sessions.json
### Current Behavior

We noticed we sometimes get an uncaught exception, it seems related to the .sessions.json file:

```
2023-06-11T10:12:32: 11 Jun 10:12:32 - [warn] Flushing file c:\runtime\service\.sessions.json to disk failed : Error: ENOENT: no such file or directory, rename 'c:\runtime\ service\.sessions.json.$$$' -> 'c:\runtime\ service\.sessions.json'
2023-06-11T10:12:32: 11 Jun 10:12:32 - [red] Uncaught Exception:
2023-06-11T10:12:32: 11 Jun 10:12:32 - [error] Error: ENOENT: no such file or directory, rename 'c:\runtime\wim\.sessions.json.$$$' -> 'c:\runtime\ service\.sessions.json'
2023-06-11T10:12:32: child process exited with code 1
```

### Expected Behavior

We assume this should not usually crash.

### Steps To Reproduce

_No response_

### Example flow

```
[{"id":"49e06aa92c948d58","type":"http request","z":"df623cb7e06fbad6","name":"","method":"POST","ret":"obj","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":710,"y":480,"wires":[[]]},{"id":"164f2c25a3828c3c","type":"function","z":"df623cb7e06fbad6","name":"getToken","func":"msg.payload = {\n  client_id: 'node-red-admin',\n  grant_type: 'password',\n  scope: 'read',\n  username: 'admin',\n  password: 'password'\n}\nmsg.url = `http://127.0.0.1:1880/auth/token`\nreturn msg","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":520,"y":480,"wires":[["49e06aa92c948d58"]]},{"id":"96c73b3086a6182f","type":"inject","z":"df623cb7e06fbad6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[1,2]","payloadType":"json","x":190,"y":480,"wires":[["9c8f35f58f210b75"]]},{"id":"9c8f35f58f210b75","type":"split","z":"df623cb7e06fbad6","name":"","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","x":350,"y":480,"wires":[["164f2c25a3828c3c"]]}]
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 18.13
- npm version: -
- Platform/OS: Windows 11
- Browser: -

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #4221 

This ensures concurrent calls to the `writeFile` utility function are serialised and handled in order. Due to the async nature of the work done, without this it was possible to hit errors (as per original issue) when multiple calls are made to update the same file.

### CODE REVIEW

File: packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/util.js [hunk 1]
```diff
@@ -71,30 +71,31 @@ function readFile(path,backupPath,emptyResponse,type) {
...
     * the write hits disk.
     */
-    writeFile: function(path,content,backupPath) {
-        var backupPromise;
-        if (backupPath && fs.existsSync(path)) {
-            backupPromise = fs.copy(path,backupPath);
-        } else {
-            backupPromise = Promise.resolve();
+    writeFile: async function(path,content,backupPath) {
+        const reqId = Math.floor(Math.random()*1000)
```
Comment (knolleary) [inline packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/util.js:83]:
```suggestion
```
