### PR TITLE
Fix the user list of nested config node

### LINKED ISSUE #4994: Since 4.0.6 update, all dashboard (v1) ui_tabs are marked as unused
### What are the steps to reproduce?
Have a v1 Dashboard with one or more ui_tabs

### What happens?
When clicking `Deploy` for changes, all ui_tabs are marked as unused nodes

image
image

### What do you expect to happen?
ui_tabs not being marked as unused unless they actually are

### Please tell us about your environment:
- Node-RED : node-red-docker@4.0.6 /usr/src/node-red
- Node.js  : v22.12.0
- npm      : 10.9.0
- Platform : Linux 6.1.0-18-amd64 x86_64
- Browser  : FireFox 133

### PR DESCRIPTION
**Pull request by GogoVega**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Fixes #4994.

#4807 removed some duplicate code that handles the user list. Unfortunately it was forgotten that config nodes can also use another config node.

During the import, the list of config nodes is sorted to ensure that nested nodes are created before updating the user list.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

File: packages/node_modules/@node-red/editor-client/src/js/nodes.js [hunk 1]
```diff
@@ -2187,6 +2194,21 @@ RED.nodes = (function() {
...
+                for (const def of Object.values(node._def.defaults)) {
+                    if (def.type) {
+                        count++;
+                    }
+                }
+            }
+            return count;
+        };
+        new_nodes.sort((a, b) => configNodeFilter(a) - configNodeFilter(b));
+
```
Comment (knolleary) [inline packages/node_modules/@node-red/editor-client/src/js/nodes.js:2211]: The old import code got this right without doing this step. I'd like to understand how these changes broke it - and if there are other scenarios related.

Comment (GogoVega) [reply packages/node_modules/@node-red/editor-client/src/js/nodes.js:2211]: The quick fix is to re-add these lines but with this way the node added to the user list is not the Proxy. So need a new loop after the `addNode` loop (2518 on dev) to replace each node object by its Proxy object.

https://github.com/node-red/node-red/blob/bb01f26f068b8e083e35fdf19dc9b36f8cf67068/packages/node_modules/%40node-red/editor-client/src/js/nodes.js#L2426-L2430

Comment (knolleary) [reply packages/node_modules/@node-red/editor-client/src/js/nodes.js:2211]: Have stepped through the logic here and am okay with this proposal.
