### PR TITLE
Properly position quick-add dialog in all cases

### LINKED ISSUE #3781: Zoomed and scrolled workspace places ghost node and "Add Node" menu incorrectly
### Current Behavior

 Ghost node and "Add Node" menu is placed incorrectly on the workspace when zoomed and scrolled

### Ghost node position OK, Add Node menu incorrect placement...

image

### Add Node position ok, ghost node incorrect placement

chrome_3uVWvSKDLS

### Expected Behavior

Should appear relative to clicked position 

### Ghost node position OK, Add Node menu incorrect placement
1. scroll horizontal 2 clicks
2. scroll vertical 2 clicks
3. zoom (`CTRL-+`) 3 clicks
4. ctrl+click in white space

### Add Node position ok, ghost node incorrect placement
1. scroll horizontal 2 clicks
2. scroll vertical 2 clicks
3. zoom (`CTRL-+`) 3 clicks
5. right click, insert, node

### Example flow

_No response_

### Environment

- Node-RED version: 3.0.0
- Node.js version: 16
- Platform/OS:  Win 11
- Browser: chrome  103.0.5060.114

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #3781

This properly takes into account both scroll and scale of the workspace when positioning the quick-add dialog.

This applies both to the Ctrl-Click opening of the dialog, and when it is opened via the context menu.

### CODE REVIEW

File: packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js [hunk 1]
```diff
@@ -44,14 +44,10 @@ RED.contextMenu = (function () {
...
         const offset = $("#red-ui-workspace-chart").offset()
 
-        let addX = options.x - offset.left + $("#red-ui-workspace-chart").scrollLeft()
-        let addY = options.y - offset.top + $("#red-ui-workspace-chart").scrollTop()
-
-        if (RED.view.snapGrid) {
-            const gridSize = RED.view.gridSize()
-            addX = gridSize * Math.floor(addX / gridSize)
-            addY = gridSize * Math.floor(addY / gridSize)
-        }
```
Comment (Steve-Mcl) [inline packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js:54]: Should we not align to grid if user option is set?

Comment (knolleary) [reply packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js:54]: The code to display the quick-add dialog already handled aligning the provided point to the grid if necessary - so no need to do it twice.
