### PR TITLE
Ensure errors in preDeliver callback are handled

### LINKED ISSUE #3848: Node Red crashing with sendEvent.destination.node.receive
### Current Behavior

```

19 Aug 09:18:58 - [red] Uncaught Exception:
19 Aug 09:18:58 - [error] TypeError: sendEvent.destination.node.receive is not a function
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:466:21)
    at process.topLevelDomainCallback (node:domain:152:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[09:18:58] WARNING: Node-RED crashed, halting add-on
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```

### Expected Behavior

Not crash? nothing has changed other than the node-red version which I updated to 3.0.2

### Steps To Reproduce

I cant tell which flow is crashing so debugging is not very easy, I dont know where to start.

### Example flow

Dont have one yet.

### Environment

- Node-RED version: 3.0,2
- Node.js version: v16.16.0
- npm version: npm@8.10.0
- Platform/OS: Home Assistant (Debian 11.3)
- Browser: Chrome

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #3848

If, for any reason, there is an error whilst delivering a message to a node, rather than cause a fatal error, it will now get logged as follows. You get the full node path, its type and the stack of the error.

```
    4 Oct 15:18:12 - [error] Error handling message: node:d5771324312036f6/dd93c1103d5aee6e [function]
    4 Oct 15:18:12 - [error] TypeError: sendEvent.destination.node.receive is not a function
        at Immediate._onImmediate (/Users/nol/code/node-red/node-red/packages/node_modules/@node-red/runtime/lib/flows/Flow.js:832:56)
        at processImmediate (node:internal/timers:464:21)
```

### CODE REVIEW

File: packages/node_modules/@node-red/runtime/lib/flows/Flow.js [hunk 1]
```diff
@@ -818,6 +818,17 @@ function handlePreRoute(flow, sendEvent, reportError) {
     })
 }
 
+function deliverMessageToDestination(sendEvent) {
+    if (sendEvent.destination.node) {
```
Comment (Steve-Mcl) [inline packages/node_modules/@node-red/runtime/lib/flows/Flow.js:822]:
```suggestion
    if (sendEvent?.destination?.node) {
```

I think we might want to be a bit more guarded here in case `sendEvent` or `destination` are null/undefined

alternatively, wrap whole thing in try/catch

File: packages/node_modules/@node-red/runtime/lib/flows/Flow.js [hunk 2]
```diff
@@ -818,6 +818,17 @@ function handlePreRoute(flow, sendEvent, reportError) {
...
+        try {
+            sendEvent.destination.node.receive(sendEvent.msg);
+        } catch(err) {
+            const info = `${sendEvent.destination.node?.id}`
```
Comment (Steve-Mcl) [inline packages/node_modules/@node-red/runtime/lib/flows/Flow.js:826]: This looks to be unused?

File: packages/node_modules/@node-red/runtime/lib/flows/Flow.js [hunk 3]
```diff
@@ -818,6 +818,17 @@ function handlePreRoute(flow, sendEvent, reportError) {
     })
 }
 
+function deliverMessageToDestination(sendEvent) {
+    if (sendEvent?.destination?.node) {
+        try {
+            sendEvent.destination.node.receive(sendEvent.msg);
+        } catch(err) {
+            const info = `${sendEvent.destination.node?.id}`
```
Comment (knolleary) [inline packages/node_modules/@node-red/runtime/lib/flows/Flow.js:826]:
```suggestion
```

**Comment by zhimsel** [comment]
I'm encountering the error this PR addresses, however, the node ID is `undefined` for me:

```
"Error delivering message to node:undefined [undefined]"

TypeError: sendEvent.destination.node.receive is not a function
    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:799:40)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:815:21)
    at processImmediate (node:internal/timers:466:21)
```

I've disabled a few contrib nodes that I don't use, but that didn't prevent the error (which is sort of expected, since they were unused.

Any thoughts? Not sure how to trace down which node is causing this...
