### PR TITLE
Fix subflow outbound-link filter

### LINKED ISSUE #4749: Loss of links when importing a copy of links into a subflow
### Current Behavior

Issue described in #4055 and on the [forum](https://discourse.nodered.org/t/link-out-link-in-in-subflows-after-copy/88506).

The issue only appears when importing a copy.

`node_map[id]` is undefined while a console.log shows that the node exists in the object.

(id, node_map, node_map[id])
Capture d’écran 2024-06-04 à 22 08 21

https://github.com/node-red/node-red/blob/61b12f6bbe3169d87637f6841075ff502f8a27e0/packages/node_modules/%40node-red/editor-client/src/js/nodes.js#L2409

### Expected Behavior

The links should not separate.

### Steps To Reproduce

Import twice the flow below into a subflow.
The first import, the links are connected.
During the second import (which is a copy), the links are separated.

### Example flow

```json
[
    {
        "id": "afbef9d1a7e911fc",
        "type": "inject",
        "z": "4abc8dbde5a2e0fb",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 230,
        "y": 60,
        "wires": [
            [
                "9fdbd0603ad12be7"
            ]
        ]
    },
    {
        "id": "dcde14acf132b58a",
        "type": "debug",
        "z": "4abc8dbde5a2e0fb",
        "name": "debug 4",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 520,
        "y": 60,
        "wires": []
    },
    {
        "id": "b3b23a6f58dc8ec5",
        "type": "link in",
        "z": "4abc8dbde5a2e0fb",
        "name": "link in 2",
        "links": [
            "9fdbd0603ad12be7"
        ],
        "x": 405,
        "y": 60,
        "wires": [
            [
                "dcde14acf132b58a"
            ]
        ]
    },
    {
        "id": "9fdbd0603ad12be7",
        "type": "link out",
        "z": "4abc8dbde5a2e0fb",
        "name": "link out 2",
        "mode": "link",
        "links": [
            "b3b23a6f58dc8ec5"
        ],
        "x": 345,
        "y": 60,
        "wires": []
    }
]
```

### Environment

- Node-RED version: 3.1.9 and 4.0.0
- Node.js version: 20.10.0
- npm version: 10.2.3
- Platform/OS: MacOS
- Browser: Safari

### PR DESCRIPTION
**Pull request by GogoVega**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Fixes #4749, completes #4750: The purpose of the filter is to prevent adding a link to a node outside the subflow.

The previous logic only filters nodes linked to the active subflow, which removes links in a child subflow.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

File: packages/node_modules/@node-red/editor-client/src/js/nodes.js [hunk 1]
```diff
@@ -2406,12 +2406,15 @@ RED.nodes = (function() {
...
+            // If importing a subflow, ensure an outbound-link doesn't get added
+            if (/^link /.test(n.type) && n.links) {
+                const isSubflow = !!getSubflow(n.z);
+                if (isSubflow) {
+                    n.links = n.links.filter(function(id) {
+                        const otherNode = node_map[id] || RED.nodes.node(id);
+                        return (otherNode && otherNode.z === n.z);
+                    });
+                }
             }
```
Comment (knolleary) [inline packages/node_modules/@node-red/editor-client/src/js/nodes.js:2418]:
```suggestion
            // If importing a link node, ensure both ends of each link are either:
            // - not in a subflow
            // - both in the same subflow
            if (/^link /.test(n.type) && n.links) {
                n.links = n.links.filter(function(id) {
                    const otherNode = node_map[id] || RED.nodes.node(id);
                    if (!otherNode) {
                        // Cannot find other end - remove the link
                        return false
                    }
                    if (otherNode.z === n.z) {
                        // Both ends in the same flow/subflow
                        return true
                    } else if (!!getSubflow(n.z) || !!getSubflow(otherNode.z)) {
                        // One end is in a subflow - remove the link
                        return false                        
                    }
                    return true
                });
            }
```

I think your proposed fix doesn't cover all the possible cases here. I've proposed an alternative that is a bit more explicit in the checks it makes - with comments to help in the future ;)

**Review by knolleary — APPROVED** [review]
