### PR TITLE
Fix node color bug

### LINKED ISSUE #1876: Node color bug
### What are the steps to reproduce?
1. git clone https://github.com/node-red/node-red.git
2. cd node-red
3. mv nodes/99-sample.html.demo nodes/99-sample.html
4. mv nodes/99-sample.js.demo nodes/99-sample.js
5. npm install
6. npm run build
7. node red.js
8. Access to Node-RED flow editor (http://locahost:1880) using browser.
9. Drag and drop sample node to work space

### What happens?
Sample node has black color because color property does not exist in 99-sample.html. Therefore, Node-RED users cannot read node name.

nodecolorbug

### What do you expect to happen?
Sample node has gray color (same as palette) in work space when color property does not exist.

### Please tell us about your environment:
- [x] Node-RED version: 0.19.2
- [x]  node.js version: 8.10.0
- [x] npm version: 3.5.2
- [x] Platform/OS: Ubuntu 18.04 (Bash on Windows 10)
- [x] Browser:68.0.3440.106 (Official Build) (64 bit)

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
I fixed #1876.

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

File: editor/js/ui/view.js [hunk 1]
```diff
@@ -2038,7 +2038,14 @@ RED.view = (function() {
                             .attr("ry",4)
                             .attr("width",16)
                             .attr("height",node_height-12)
-                            .attr("fill",function(d) { return RED.utils.getNodeColor(d.type,d._def); /*d._def.color;*/})
+                            .attr("fill", function (d) {
+                                var nodeColor = RED.utils.getNodeColor(d.type,d._def); /*d._def.color;*/
```
Comment (knolleary) [inline editor/js/ui/view.js]: I think it would be better to have `RED.utils.getNodeColor` return a default colour, rather than have to add this same logic in multiple places.

Comment (kazuhitoyokoi) [reply editor/js/ui/view.js]: @knolleary That's right. I'll add the logic into getNodeColor() in editor/js/ui/utils.js.

**Comment by kazuhitoyokoi** [comment]
@knolleary Thank you. 👍
