### PR TITLE
Fix wrong unlock state when event is triggered after deployment

### LINKED ISSUE #4888: Lock icon disappear when deploying
### Current Behavior

When I lock a flow from the information sidebar and I click on deploy (it doesn't matter which one) the lock icon of the flow disappear and comes back when I fully reload the site.

### Expected Behavior

Flow locked Icon should still be visible when clicking on Deploy.

### Steps To Reproduce

1. Click on the lock icon of a flow from the information tab.
2. Click on Deploy (doesn't matter which one).
Now lock icon disappeared from the flow that needs to be locked.

### Example flow

_No response_

### Environment

- Node-RED version: 4.0.2
- Node.js version: 20.17.0
- npm version: 20 I guess
- Platform/OS: FlowFuse
- Browser: Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by GogoVega**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Fixes #4888.

In order to modify nodes, subflows/workspaces are temporarily unlocked.

An event is triggered for any subflow/workspace that has changed. This event will always contain an **unlocked** workspace because the re-locking only happens after all events have been triggered.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

File: packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js [hunk 1]
```diff
@@ -653,9 +657,13 @@ RED.deploy = (function() {
                     ensureUnlocked(ws.z)
```
Comment (GogoVega) [inline packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js:657]: If I'm not mistaken, workspaces don't have a `z` property.
```suggestion
```

File: packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js [hunk 2]
```diff
@@ -645,6 +646,9 @@ RED.deploy = (function() {
             RED.nodes.eachSubflow(function (subflow) {
                 if (subflow.changed) {
                     subflow.changed = false;
+                    if (flowsToLock.has(subflow)) {
+                        subflow.locked = true;
+                    }
```
Comment (knolleary) [inline packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js:651]:
```suggestion
```

Subflows cannot be locked

File: packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js (hunk 1 above)
Comment (knolleary) [inline packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js:657]:
```suggestion
                    ensureUnlocked(ws.id)
```

We should ensure the flow is unlocked - so pass in its own id. If the flow contains any nodes, it will already have been temporarily unlocked. This handles the edge case the flow is empty.

File: packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js [hunk 3]
```diff
@@ -653,9 +657,13 @@ RED.deploy = (function() {
                     ensureUnlocked(ws.z)
                     ws.changed = false;
                     delete ws.added
+                    if (flowsToLock.has(ws)) {
+                        ws.locked = true;
```
Comment (knolleary) [inline packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js:661]:
```suggestion
                        ws.locked = true;
                        flowsToLock.delete(ws);
```

To keep things tidy, remove from flowsToLock so we don't lock it again later. It's pretty harmless, but keeps `flowsToLock` as an accurate set of things to be locked later.

**Review by knolleary — CHANGES_REQUESTED** [review]

File: packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js (hunk 1 above)
Comment (GogoVega) [reply packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js:657]: I had thought about this case but if it does not contain a node, there is nothing to modify right?

Comment (knolleary) [reply packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js:657]: we are modifying the properties of the flow itself, so yes, we are modifying it.

File: packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js [hunk 4]
```diff
@@ -589,6 +589,7 @@ RED.deploy = (function() {
                 RED.notify('<p>' + RED._("deploy.successfulDeploy") + '</p>', "success");
             }
             const flowsToLock = new Set()
+            // Node's properties cannot be modified if its workspace is locked.
             function ensureUnlocked(id) {
                 const flow = id && (RED.nodes.workspace(id) || RED.nodes.subflow(id) || null);
```
Comment (GogoVega) [inline packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js:594]: If the Subflow cannot be locked, why do we check `RED.nodes.subflow(id)`?

File: packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js (hunk 1 above)
Comment (GogoVega) [reply packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js]: I don't see a Proxy Handler on the Workspace. I put in case the `ensureUnlocked` function but I don't think if it's really used.
