### PR TITLE
Fix storing subflow credential type when input has multiple types

### LINKED ISSUE #3749: Entered password is lost from subflow instance when the subflow instance is edited
### Current Behavior

Similar to issue #3641 - the password setting is lost when a subflow field is set to input and has a credential option

image

Here is what happens (Also, see GIF below)
* Subflow instance has 2 password fields (1 is a credential type, the 2nd is a typed input with str, env and credential types)
* Entering passwords for both then deploying works as expected
* Re-opeing the subflow instance we can see the password for `password2` is empty.
* Changing something unrelated (like the nodes name) and deploying proves the password has been lost from the editor and runtime

chrome_j0vWy7CzBA

### Expected Behavior

Similar to how the credential type field works, the input type field with a credential option should retain its value.

### Steps To Reproduce

* Import flow
* Enter passwords for both fields
* deploy
* operate inject
  * confirm `password` and `password2` have value
* open the subflow instance editor
* change the name of the node instance
* deploy
* inject
  * `password2` is now empty

### Example flow

```
[{"id":"9b4ba4afc154141e","type":"subflow","name":"Subflow 1","info":"","category":"","in":[{"x":320,"y":280,"wires":[{"id":"0ed3b277a67aac21"}]}],"out":[{"x":620,"y":380,"wires":[{"id":"0ed3b277a67aac21","port":0}]}],"env":[{"name":"password","type":"cred"},{"name":"password2","type":"cred","ui":{"type":"input","opts":{"types":["str","env","cred"]}}}],"meta":{},"credentials":{"password":"","password2":""},"color":"#DDAA99"},{"id":"02a4f076515317df","type":"change","z":"9b4ba4afc154141e","name":"add","rules":[{"t":"set","p":"payload","pt":"msg","to":"$sum(payload)\t","tot":"jsonata"},{"t":"set","p":"password","pt":"msg","to":"password","tot":"env"},{"t":"set","p":"password2","pt":"msg","to":"password2","tot":"env"}],"action":"","property":"","from":"","to":"","reg":false,"x":450,"y":200,"wires":[["3fcf9edba923d003"]]},{"id":"fa99afd2b57e85c7","type":"link in","z":"9b4ba4afc154141e","name":"add","links":[],"x":350,"y":200,"wires":[["02a4f076515317df"]]},{"id":"3fcf9edba923d003","type":"link out","z":"9b4ba4afc154141e","name":"link out 9","mode":"return","links":[],"x":570,"y":200,"wires":[]},{"id":"0ed3b277a67aac21","type":"link call","z":"9b4ba4afc154141e","name":"","links":["fa99afd2b57e85c7"],"linkType":"static","timeout":"30","x":500,"y":280,"wires":[[]]},{"id":"affbc1a2ae946e28","type":"subflow:9b4ba4afc154141e","z":"8fb7704d922a7884","name":"test","env":[{"name":"password","type":"cred"},{"name":"password2","type":"cred"}],"credentials":{"password":"__PWRD__","password2":""},"x":910,"y":140,"wires":[["1da8b2c815270524"]]},{"id":"c378e1919f5383cd","type":"inject","z":"8fb7704d922a7884","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":920,"y":80,"wires":[["affbc1a2ae946e28"]]},{"id":"1da8b2c815270524","type":"debug","z":"8fb7704d922a7884","name":"debug 40","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1120,"y":140,"wires":[]}]
```

### Environment

- Node-RED version: V3 beta4/5 (current master branch as of writing)
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #3749

If a subflow property has a UI defined with multiple types, including credential - the value is lost if the type is set to credential. This fix ensure the value does not get lost.

### CODE REVIEW

File: packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js [hunk 1]
```diff
@@ -931,6 +931,7 @@ RED.subflow = (function() {
 
 
     function buildEnvUIRow(row, tenv, ui, node) {
+        console.log(tenv, ui)
```
Comment (Steve-Mcl) [inline packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js:934]:
```suggestion
```

**Review by Steve-Mcl — COMMENTED** [review]
All good apart from the console.log 👍
