### PR TITLE
Handle link nodes with show/hide label action

### LINKED ISSUE #5090: Link In/Out Nodes Can't Show Labels From The Right-Click Menu
### Current Behavior

A newly added Link-In or Link-Out node does not have the right-click menu option to show selected node label.

Image

If you enter the node properties and manually tick the box to show the label, then the menu options work as normal again

### Expected Behavior

The option to show the label should be present

### Steps To Reproduce

1. Add a link-in or link-out node to your workspace
2. Right-click the newly added node
3. Select "Node >" menu option
4. See that the Show option is disabled, while the Hide is enabled - see above screenshot

### Example flow

N/A

### Environment

- Node-RED : node-red-docker@4.0.9 /usr/src/node-red
- Node.js  : v22.14.0
- npm      : 10.9.2
- Platform : Linux 6.1.0-18-amd64 x86_64
- Browser  : FireFox 136

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #5090 

The code that determined whether to enable the show/hide label context menu items was not handling the link nodes properly.

If a node doesn't have an `l` property, we need to check if `showLabel` is set on its definition to see what the default value of `l` should be. We cannot assume that lack of an `l` property means the label is shown - as link nodes set `showLabel` to false.

Whilst verifying this fix, I also spotted the history handling of the show/hide action was also incorrect. It was also  it was setting the old value to the wrong default (without taking into account the `showLabel` value).

### CODE REVIEW

File: packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js [hunk 1]
```diff
@@ -176,8 +176,8 @@ RED.view.tools = (function() {
         }
         nodes.forEach(function(n) {
             var modified = false;
-            var oldValue = n.l === undefined?true:n.l;
-            var showLabel = n._def.hasOwnProperty("showLabel")?n._def.showLabel:true;
+            var showLabel = n._def.hasOwnProperty("showLabel") ? n._def.showLabel : true;
```
Comment (GogoVega) [inline packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js:179]: Wouldn't it be better to use the "editor.view.view-node-show-label" parameter as the default value (instead of true) ?
